# Generated by Django 6.1 on 2026-08-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='holiday_balance',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
